### ISSUE TITLE
Code is not consistent (internally)

### ISSUE THREAD

**Issue by LocutusOfPenguin** [zendframework/zend-navigation#28]
Hi,
1)
in src/Service/AbstractNavigationFactory.php
this seems to not be consistent (see: ServiceLocatorInterface / ContainerInterface)

```
    /**
     * Create and return a new Navigation instance (v2).
     *
     * @param ContainerInterface $container
     * @param null|string $name
     * @param null|string $requestedName
     * @return Navigation
     */
    public function createService(ServiceLocatorInterface $container, $name = null, $requestedName = null)
    {
        return $this($container, $requestedName);
    }
```

2)
If i want to filter the pages with ZfcRbac (=>user rights) where should i do that?  in getPages() or better use preparePages() or even somewhere else?

Thanks!

**Comment by froschdesign** [comment]
Will be closed. An explanation can be found at the [related PR](https://github.com/zendframework/zend-navigation/pull/51#issuecomment-287826757).
