### ISSUE TITLE
Zend Navigation with Zend Expressive  - localization ?

### ISSUE THREAD

**Issue by unnamed666** [zendframework/zend-navigation#64]
hi, i have a little question about Zend Navigataion.
After following cookbook tutorial about setting locale without url param (https://docs.zendframework.com/zend-expressive/cookbook/setting-locale-without-routing-parameter/) i am a bit confused so maybe someone can help me here.

If i enter url like local.com/en/some-page
my locale is set to english and all urls created with UrlHelper get '/en' part prepended
but Zend Navigation is still rendering url without that '/en' part.

What should i do to make Zend Navigation prepend that '/en/' part to all created links just like UrlHelper?
ps. i am using froschdesign/zend-navigation - feature/expressive-support branch

**Comment by froschdesign** [comment]
@unnamed666 
> my locale is set to english and all urls created with UrlHelper get '/en' part prepended
but Zend Navigation is still rendering url without that '/en' part.

The page type `Expressive` doesn't use the `Zend\Expressive\Helper\UrlHelper` to generate the URLs. The Router is used.
The ZF router also interacts with a base URL, maybe this is a solution.

**Comment by froschdesign** [comment]
@unnamed666 
I worked on a solution to fix the problem. I will update my `feature/expressive-support` branch in the next days.

Thanks for your patience!

**Comment by froschdesign** [comment]
@unnamed666 
This fix your problem:

https://github.com/froschdesign/zend-expressive-navigation/blob/master/test/Page/ExpressivePageTest.php#L112-L127

**Comment by froschdesign** [comment]
The support of zend-expressive will not be a part of this component. It is include a new component "zend-expressive-navigation" and also the UrlHelper with the base path.

Thanks for the hint! 👍
