### ISSUE TITLE
Trouble with multiple navigations in ZF3

### ISSUE THREAD

**Issue by rustedwolf** [zendframework/zend-navigation#68]
I've created navigation in the configuration file, according to example in Quick Star documentation. It worked with single menu, but once I've tried multiple menu approach I receive the following error:

> Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "ZendNavigationDefault" to a factory; are you certain you provided it during configuration?

The way I call the methof
`{% for page in navigation('Zend\Navigation\Default').container %}
      <a href="{{ url(page.route) }}" class="navbar-item">{{ page.label }}</a>
  {% endfor %}`

**Comment by froschdesign** [comment]
@rustedwolf 
If you look at the error message, you will see that slashes are missing:

> "ZendNavigationDefault"

Add extra slashes:

```php
{% for page in navigation('Zend\\Navigation\\Default').container %} … {% endfor %}
```
The slashes are only needed in a Twig template.

**Comment by rustedwolf** [comment]
Thanks, that helped!
