### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by sebfek** [zendframework/zend-navigation#7]
- Better support for dynamic builded navigations instead hardcoded configuration array
- Put the different dynamic navigations factories to an own plugin manager (maybe)
- Support to set the default active page. Example:
  Mypage - /test -> Should point to Mysubpage 1
  Mysubpage 1 - /test/page1
  Mysubpage 2 - /test/page2
- Make the Mvc (Page) more compact and move the logic (example isActive) to the Navigation class.
- The View Helper Navigation\Menu renderPartial method shold accept additional parameters you want to pass to the partial.

**Comment by froschdesign** [comment]
> Better support for dynamic builded navigations instead hardcoded configuration array

It is very simple: Create an own factory.

> Put the different dynamic navigations factories to an own plugin manager (maybe)

And then? Where is the benefit?

> Support to set the default active page. Example: Mypage - /test -> Should point to Mysubpage 1 Mysubpage 1 - /test/page1 Mysubpage 2 - /test/page2

- Foo
    - Bar
    - Baz

If "Foo" is active, then should "Bar" and "Baz" also active?

> Make the Mvc (Page) more compact and move the logic (example isActive) to the Navigation class.

`RouteMatch` is only important for the `Mvc` page type. Why would you move this to the navigation class?

> The View Helper Navigation\Menu renderPartial method shold accept additional parameters you want to pass to the partial.

[This is already implemented.](https://github.com/zendframework/zend-view/blob/master/src/Helper/Navigation/Menu.php#L396)

**Comment by froschdesign** [comment]
Closing due inactivity.
